version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      # - QDRANT_URL=http://qdrant:6333
      - QDRANT_URL=https://qdrant-production-0384.up.railway.app
      - PYTHONUNBUFFERED=1
    depends_on:
      - qdrant
    networks:
      - app-network
    volumes:
      - .:/app
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8080",
        "--workers",
        "1",
        "--timeout",
        "120",
        "--reload",
        "api:app",
      ]

volumes:
  qdrant_storage:

networks:
  app-network:
    driver: bridge
